name: Export JSON

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate JSON
        run: node index.js

      - name: Clone target repo
        env:
          GIT_ASKPASS: /bin/echo
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/HytaleTracker/HytaleTracker.github.io.git target

      - name: Copy file
        run: |
          mkdir -p target/data
          cp data/devs-post-revival.json target/data/devs-post-revival.json

      - name: Commit & push
        run: |
          cd target
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update JSON" || true
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
